name: CI
on:
push:
branches: [ "develop", "feature/*" ]
pull_request:
branches: [ "develop" ]


jobs:
lint-test-build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Set up Python
uses: actions/setup-python@v4
with:
python-version: '3.10'
- name: Install deps
run: |
python -m pip install --upgrade pip
pip install -r requirements-dev.txt
- name: Lint
run: pylint odoo_addons || true
- name: Unit tests
run: pytest -q || true
- name: Build and push Docker image
if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
uses: docker/build-push-action@v4
with:
context: .
file: ./docker/odoo.Dockerfile
push: true
tags: ghcr.io/${{ github.repository_owner }}/odoo-custom:${{ github.sha }}
